export default {
  authed: false,
  token: '',
  quoteData: [
    isFetching: false,
    askPrice: '',
    askSize: '',
    bidPrice: '',
    bidSize: '',
    lastTradePrice: '',
    lastExtendedHoursTradePrice: '',
    previousClose: '',
    previousCloseDate: '',
    symbol: '',
    trading_halted: false,
    updated_at: '',
    fundamentals: [
      open: '',
      high: '',
      low: '',
      volume: '',
      averageVolume: '',
      high52Weeks: '',
      dividendYield: '',
      low52Weeks: '',
      marketCap: '',
      peRation: '',
      description: '',
      instrument: '',
    ]
  ],
  accountData: [
    userId: [
      username: '',
      url: '',
      id: '',
    ],
    auth: [
      username: '',
      firstName: '',
      lastName: '',
      idInfo: '',
      url: '',
      basicInfo: '',
      email: '',
      investmentProfile: '',
      id: '',
      internationalInfo: '',
      employment: '',
      additionalInfo: '',
    ],
    portfolio: [
      account: '',
      adjustedEquityPreviousClose: '',
      equity: '',
      equityPreviousClose: '',
      excessMaintenance: '',
      excessMaintenanceWithUnclearedDeposits: '',
      extendedHoursEquity: '',
      extendedHoursMarketValue: '',
      lastCoreEquity: '',
      lastCoreMarketValue: '',
      marketValue: '',
      startDate: '',
      unwithdrawableDeposits: '',
      url: '',
      withdrawableAmount: '',
    ],
    basicInfo: [
      phoneNumber: '',
      city: '',
      numberDependents: '',
      citizenship: '',
      updatedAt: '',
      maritalStatus: '',
      zipcode: '',
      countryOfResidence: '',
      state: '',
      dateOfBirth: '',
      user: '',
      address: '',
      taxIdSsn: '',
    ]
  ],
  order: [
    account: '',
    instrument: '',
    symbol: '',
    type: '',
    time_in_force: '',
    trigger: '',
    price: '',
    stop_price: '',
    quantity: '',
    side: '',
    client_id: '',
  ],
};
